### PR TITLE
update address on footer

### PR DESCRIPTION
**Pull request by XertroV**

### CODE REVIEW

**Comment by XertroV** [comment]
@okdaithi look okay?

**Comment by XertroV** [comment]
> ### Deploy Preview for branch 2020-07-17-update-addr
> #### Commit: [dc774cb](https://github.com/voteflux/flux-website-v2/commit/dc774cb94ae51012f663028ceec078f4c1383c53)
> undefined
> 
> 🎉

hmm. bugger

**Comment by XertroV** [comment]
Well, you can just check the code; there's not much which is changed

**Comment by XertroV** [comment]
awaiting approval of application for addr in PR, eta 2-3 business days

**Comment by okdaithi** [comment]
Address has been confirmed. Can confirm changes.

**Pull request merged**
