### PR TITLE
AD-24 Team WA Page

### PR DESCRIPTION
**Pull request by TomSesselmann**
Adds a new page https://voteflux.org/wa-team (maybe should change to https://voteflux.org/flux-wa/team)
Copied mostly from https://voteflux.org/candidates/

Still need to add some text at the top. I think I might get Daithi to write that.

### CODE REVIEW

**Comment by TomSesselmann** [comment]
Oh and there is no link to this page at the moment.

**Comment by XertroV** [comment]
Looks pretty good! https://deploy-preview-25--voteflux.netlify.com/wa-team/

Happy to ACK but we'll need to update the "Flux Senators" thing at the top. An easy fix is to replace "Senators" with "Representatives" or maybe "Representatives and Team" sort of thing.

**Comment by TomSesselmann** [comment]
screencapture-localhost-9000-wa-team-1484778716582

**Comment by XertroV** [comment]
Also I agree we should settle on URLs that make sense
I think:
`voteflux.org/wa/team` makes the most sense, and we can carry that through to the WP version when we migrate. You can imagine 'us.fluxparty.org/california` too (or maybe `/CA`)

**Comment by XertroV** [comment]
Actually, given the above, NACK till we can fix those issues up:

* URL
* Senators

Then we can link to this page in a new PR (we can add it to the navbar maybe?)

**Comment by Amaroni** [comment]
Making minor edits, to titles

**Review by XertroV — APPROVED** [review]
ACK, I think we're good.

**Comment by XertroV** [comment]
@TomSesselmann merge PR when ready :)

**Comment by TomSesselmann** [comment]
screen shot 2017-01-19 at 11 53 33 am

**Pull request merged**
