### PR TITLE
Add wa team positions back

### PR DESCRIPTION
**Pull request by TomSesselmann**
screen shot 2017-02-06 at 5 37 29 pm

### CODE REVIEW

**Comment by ghost** [comment]
Your pull request doesn't follow our guidelines. Please fix the following:

* Pull request description must include a screenshot [(?)](https://gitmagic.io/rules/#/pull-request/body-must-include-screenshot)
* Pull request description cannot be empty [(?)](https://gitmagic.io/rules/#/pull-request/body-cannot-be-empty)
* Pull request title must start with uppercase [(?)](https://gitmagic.io/rules/#/pull-request/subject-must-start-with-case)

[Click here](https://app.gitmagic.io/voteflux/vote-flux-v2/39/72c10fe5-5217-412a-b376-32a0e80ee5ee/2d7b4f6a-0b7f-4aa4-bbce-1ae76412c830) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
This pull request still violates some of our guidelines:

* Pull request description must include a screenshot [(?)](https://gitmagic.io/rules/#/pull-request/body-must-include-screenshot)
* Pull request description cannot be empty [(?)](https://gitmagic.io/rules/#/pull-request/body-cannot-be-empty)

[Click here](https://app.gitmagic.io/voteflux/vote-flux-v2/39/72c10fe5-5217-412a-b376-32a0e80ee5ee/2d7b4f6a-0b7f-4aa4-bbce-1ae76412c830) for details.

**Comment by ghost** [comment]
Thank you, the title and description now looks good! :bowtie:

**Comment by XertroV** [comment]
Looks good - ACK once dev preview has been checked

**Review by XertroV — APPROVED** [review]

**Pull request merged**
